// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEt6MB9kPB5LK63bQkHHLh3b05ZPpNlm0',
    appId: '1:159556622178:web:6ac63775994b70d0e2fe3b',
    messagingSenderId: '159556622178',
    projectId: 'healthmonitorapp-9abc9',
    authDomain: 'healthmonitorapp-9abc9.firebaseapp.com',
    storageBucket: 'healthmonitorapp-9abc9.firebasestorage.app',
    measurementId: 'G-HWPBDWFQF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADlb0Xy0pZP6rUyzefOJaL2DZvQp6YDO0',
    appId: '1:159556622178:android:d935ac0ca5fd3397e2fe3b',
    messagingSenderId: '159556622178',
    projectId: 'healthmonitorapp-9abc9',
    storageBucket: 'healthmonitorapp-9abc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ZKTB2j3f241y2KFVdk-sr5mkOcyY0C0',
    appId: '1:159556622178:ios:124fba2b37bd010ae2fe3b',
    messagingSenderId: '159556622178',
    projectId: 'healthmonitorapp-9abc9',
    storageBucket: 'healthmonitorapp-9abc9.firebasestorage.app',
    iosBundleId: 'com.example.healthmonitorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ZKTB2j3f241y2KFVdk-sr5mkOcyY0C0',
    appId: '1:159556622178:ios:124fba2b37bd010ae2fe3b',
    messagingSenderId: '159556622178',
    projectId: 'healthmonitorapp-9abc9',
    storageBucket: 'healthmonitorapp-9abc9.firebasestorage.app',
    iosBundleId: 'com.example.healthmonitorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEt6MB9kPB5LK63bQkHHLh3b05ZPpNlm0',
    appId: '1:159556622178:web:c497fe7b66c7868ae2fe3b',
    messagingSenderId: '159556622178',
    projectId: 'healthmonitorapp-9abc9',
    authDomain: 'healthmonitorapp-9abc9.firebaseapp.com',
    storageBucket: 'healthmonitorapp-9abc9.firebasestorage.app',
    measurementId: 'G-79JSC49LJD',
  );

}