// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixnNUI5VGbTeSw4XWFDEOG8NcybZk8BY',
    appId: '1:371859837216:web:0a7687e37c3649f48b4745',
    messagingSenderId: '371859837216',
    projectId: 'healthmonitorapp-79db5',
    authDomain: 'healthmonitorapp-79db5.firebaseapp.com',
    storageBucket: 'healthmonitorapp-79db5.firebasestorage.app',
    measurementId: 'G-SPM5PZBSMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrIaCYueG-f0SAeLnEhWGYhcS91iFC_vw',
    appId: '1:371859837216:android:9a638896ff892f948b4745',
    messagingSenderId: '371859837216',
    projectId: 'healthmonitorapp-79db5',
    storageBucket: 'healthmonitorapp-79db5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE53myfcTaKFkSdZg3dNIk7zqZoVuzkzg',
    appId: '1:371859837216:ios:beffd1f500ef0dfc8b4745',
    messagingSenderId: '371859837216',
    projectId: 'healthmonitorapp-79db5',
    storageBucket: 'healthmonitorapp-79db5.firebasestorage.app',
    iosBundleId: 'com.example.healthmonitorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE53myfcTaKFkSdZg3dNIk7zqZoVuzkzg',
    appId: '1:371859837216:ios:beffd1f500ef0dfc8b4745',
    messagingSenderId: '371859837216',
    projectId: 'healthmonitorapp-79db5',
    storageBucket: 'healthmonitorapp-79db5.firebasestorage.app',
    iosBundleId: 'com.example.healthmonitorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAixnNUI5VGbTeSw4XWFDEOG8NcybZk8BY',
    appId: '1:371859837216:web:b84159428cd40e4c8b4745',
    messagingSenderId: '371859837216',
    projectId: 'healthmonitorapp-79db5',
    authDomain: 'healthmonitorapp-79db5.firebaseapp.com',
    storageBucket: 'healthmonitorapp-79db5.firebasestorage.app',
    measurementId: 'G-3JM61S8T5Q',
  );
}
